apiVersion: v2
appVersion: latest
description: SearXNG is a free internet metasearch engine which aggregates results from various search services and databases.
name: searxng
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - searx
  - searxng
  - search engine
  - privacy
icon: https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/img/favicon.png?raw=true
sources:
  - https://github.com/searxng/searxng
  - https://docs.searxng.org
  - https://hub.docker.com/r/searxng/searxng
maintainers:
  - name: unixfox
    email: searxngatunixfoxdoteu
dependencies:
  - name: helmet
    version: 0.11.0
    repository: https://charts.companyinfo.dev
    import-values: # <== It is mandatory if you want to import the Helmet default values.
      - defaults  
  - name: redis
    version: 0.0.3
    repository: https://charts.pascaliske.dev
    condition: redis.enabled
