#
# IMPORTANT NOTE
#
# This chart inherits from Helmet library chart. You can check the default values/options here:
# https://github.com/companyinfo/helm-charts/tree/main/charts/helmet
#

image:
  repository: searxng/searxng
  tag: latest
  pullPolicy: Always
  
ports:
  - name: http
    containerPort: 8080
    protocol: TCP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: search.mydomain.com
  # configure tls with cert-manager
  tls: false
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"

configMap:
  mounted: true
  mountPath: /etc/searxng/settings.yml
  subPath: "searxng"
  data:
    searxng: |
      use_default_settings: true
      general:
        instance_name: "searxng-mydomain"
      server:
        secret_key: "mysecretkeythatishouldchange"
        bind_address: "0.0.0.0:8080"
        base_url: "https://search.mydomain.com/"
      search:
        formats:
          - html
          - json  

readinessProbe:
  enabled: false
  httpGet:
    path: /healthz
    port: 8080
livenessProbe:
  enabled: false
  httpGet:
    path: /healthz
    port: 8080
startupProbe:
  enabled: false
  httpGet:
    path: /healthz
    port: 8080

# Enable when using searxng builtin rate limiter
# Values: https://github.com/pascaliske/helm-charts/tree/master/charts/redis
redis:
  enabled: false
